import { CalendarDays, CircleDollarSign, Package, ShoppingBag, TrendingDown, TrendingUp, Users } from 'lucide-react'
import PageHeader from '@/components/dashboard/page-header'
import { orders } from '@/lib/admin-data'

export default function DashboardPage() {
  return <div className="dashboard-content"><PageHeader eyebrow="CONTROL CENTER" title="Dashboard overview" description="Here’s what’s happening with GECES today." action={<><button className="outline-button">Export report</button><button className="primary-button">+ New booking</button></>}/><section className="stats-grid"><Stat title="Total revenue" value="₦4,286,500" delta="12.5%" icon={<CircleDollarSign/>}/><Stat title="Total bookings" value="84" delta="8.2%" icon={<CalendarDays/>}/><Stat title="Customers" value="1,429" delta="5.7%" icon={<Users/>}/><Stat title="Pending orders" value="18" delta="2.4%" icon={<Package/>} down/></section><section className="analytics-grid"><article className="panel revenue-panel"><div className="panel-heading"><div><h2>Revenue overview</h2><p>Monthly catering and event revenue</p></div><select aria-label="Revenue period"><option>30 days</option><option>90 days</option></select></div><div className="chart-summary"><strong>₦2,186,500</strong><span><TrendingUp size={14}/>14.6%</span><em>this period</em></div><div className="bar-chart" aria-label="Revenue chart">{[42,58,48,76,63,88,72,96,82,100].map((height,index)=><div key={index}><i style={{height:`${height}%`}}/><span>{index % 2 === 0 ? `W${index/2+1}` : ''}</span></div>)}</div></article><article className="panel products-panel"><div className="panel-heading"><div><h2>Operations pulse</h2><p>Live business summary</p></div></div><div className="pulse-list"><div><span className="pulse-icon gold"><ShoppingBag/></span><div><strong>12 new orders</strong><span>4 require confirmation</span></div></div><div><span className="pulse-icon green"><CalendarDays/></span><div><strong>6 upcoming events</strong><span>Next event in 3 days</span></div></div><div><span className="pulse-icon rose"><Users/></span><div><strong>28 new enquiries</strong><span>Up 18% this week</span></div></div></div></article></section><section className="panel orders-panel"><div className="panel-heading orders-heading"><div><h2>Recent orders</h2><p>Latest customer activity</p></div></div><div className="table-wrap"><table><thead><tr><th>Order</th><th>Customer</th><th>Product</th><th>Date</th><th>Total</th><th>Status</th></tr></thead><tbody>{orders.map(order=><tr key={order.id}><td><strong>#{order.id}</strong></td><td><strong>{order.customer}</strong></td><td>{order.item}</td><td>{order.date}</td><td><strong>{order.total}</strong></td><td><span className={`status ${order.status.toLowerCase()}`}>{order.status}</span></td></tr>)}</tbody></table></div></section></div>
}

function Stat({title,value,delta,icon,down=false}:{title:string;value:string;delta:string;icon:React.ReactNode;down?:boolean}){return <article className="stat-card"><div className="stat-icon gold">{icon}</div><div className="stat-copy"><span>{title}</span><strong>{value}</strong><p className={down?'down':''}>{down?<TrendingDown size={14}/>:<TrendingUp size={14}/>}<b>{delta}</b> vs last month</p></div></article>}
