import { Router } from "express"
import { Role, VendorStatus, WithdrawalStatus, QuoteStatus, BookingStatus, TransactionStatus, TransactionType } from "@prisma/client"
import { z } from "zod"
import { prisma } from "../lib/prisma.js"
import { authenticate, authorize } from "../middleware/auth.js"
import { asyncHandler } from "../middleware/async-handler.js"
import { AppError } from "../middleware/errors.js"

export const adminRouter = Router()
adminRouter.use(authenticate, authorize(Role.SUPER_ADMIN))

adminRouter.get("/dashboard", asyncHandler(async (_req, res) => { const [customers, vendors, orders, withdrawals, revenue, commission] = await Promise.all([prisma.user.count({ where: { role: Role.CUSTOMER } }), prisma.vendorProfile.count(), prisma.order.count(), prisma.withdrawal.count({ where: { status: WithdrawalStatus.PENDING } }), prisma.platformWallet.findUnique({ where: { id: "platform" } }), prisma.transaction.aggregate({ where: { type: TransactionType.COMMISSION, status: TransactionStatus.SUCCESS }, _sum: { amount: true } })]); res.json({ success: true, data: { totalCustomers: customers, totalVendors: vendors, totalOrders: orders, pendingWithdrawals: withdrawals, totalPlatformRevenue: revenue?.balance ?? 0, commissionEarned: commission._sum.amount ?? 0 } }) }))
adminRouter.get("/users", asyncHandler(async (req, res) => { const role = req.query.role as Role | undefined; const rows = await prisma.user.findMany({ where: { ...(role && { role }) }, select: { id: true, name: true, email: true, phone: true, role: true, isActive: true, createdAt: true, vendorProfile: { select: { id: true, businessName: true, status: true } } }, orderBy: { createdAt: "desc" } }); res.json({ success: true, data: rows }) }))
adminRouter.patch("/users/:id", asyncHandler(async (req, res) => { const data = z.object({ role: z.nativeEnum(Role).optional(), isActive: z.boolean().optional() }).parse(req.body); if (req.params.id === req.auth!.sub && (data.isActive === false || (data.role && data.role !== Role.SUPER_ADMIN))) throw new AppError(409, "SELF_LOCKOUT", "You cannot remove your own Super Admin access."); const user = await prisma.user.update({ where: { id: req.params.id }, data, select: { id: true, name: true, email: true, role: true, isActive: true } }); res.json({ success: true, data: user }) }))
adminRouter.get("/vendors", asyncHandler(async (req, res) => { const status = req.query.status as VendorStatus | undefined; res.json({ success: true, data: await prisma.vendorProfile.findMany({ where: { ...(status && { status }) }, include: { user: { select: { name: true, email: true } }, wallet: true, _count: { select: { products: true, orders: true } } }, orderBy: { createdAt: "desc" } }) }) }))
adminRouter.patch("/vendors/:id/status", asyncHandler(async (req, res) => { const { status } = z.object({ status: z.nativeEnum(VendorStatus) }).parse(req.body); const vendor = await prisma.vendorProfile.update({ where: { id: req.params.id }, data: { status } }); await prisma.auditLog.create({ data: { actorId: req.auth!.sub, action: `VENDOR_${status}`, entity: "VendorProfile", entityId: vendor.id } }); res.json({ success: true, data: vendor }) }))
adminRouter.get("/orders", asyncHandler(async (_req, res) => { res.json({ success: true, data: await prisma.order.findMany({ include: { customer: { select: { name: true, email: true } }, vendor: { select: { businessName: true } }, items: true }, orderBy: { createdAt: "desc" }, take: 500 }) }) }))
adminRouter.get("/withdrawals", asyncHandler(async (req, res) => { const status = req.query.status as WithdrawalStatus | undefined; res.json({ success: true, data: await prisma.withdrawal.findMany({ where: { ...(status && { status }) }, include: { vendor: { include: { user: { select: { name: true, email: true } } } } }, orderBy: { requestedAt: "desc" } }) }) }))
adminRouter.patch("/withdrawals/:id/status", asyncHandler(async (req, res) => { const { status } = z.object({ status: z.enum(["APPROVED", "REJECTED", "PAID"]) }).parse(req.body); const current = await prisma.withdrawal.findUnique({ where: { id: req.params.id } }); if (!current) throw new AppError(404, "WITHDRAWAL_NOT_FOUND", "Withdrawal not found."); if (current.status === WithdrawalStatus.PAID || current.status === WithdrawalStatus.REJECTED) throw new AppError(409, "WITHDRAWAL_FINAL", "This withdrawal has already reached a final state."); const updated = await prisma.$transaction(async tx => { if (status === "REJECTED") await tx.vendorWallet.update({ where: { vendorId: current.vendorId }, data: { availableBalance: { increment: current.amount } } }); if (status === "PAID") await tx.transaction.create({ data: { vendorId: current.vendorId, amount: current.amount, type: TransactionType.PAYOUT, status: TransactionStatus.SUCCESS } }); return tx.withdrawal.update({ where: { id: current.id }, data: { status: status as WithdrawalStatus, processedAt: new Date() } }) }); res.json({ success: true, data: updated }) }))
adminRouter.get("/commission", asyncHandler(async (_req, res) => { res.json({ success: true, data: await prisma.commissionSetting.findUnique({ where: { id: "default" } }) }) }))
adminRouter.patch("/commission", asyncHandler(async (req, res) => { const { rate } = z.object({ rate: z.number().min(0).max(100) }).parse(req.body); const setting = await prisma.commissionSetting.upsert({ where: { id: "default" }, update: { rate }, create: { id: "default", rate } }); res.json({ success: true, data: setting }) }))
adminRouter.get("/transactions", asyncHandler(async (_req, res) => { res.json({ success: true, data: await prisma.transaction.findMany({ include: { vendor: { select: { businessName: true } }, order: { select: { orderNumber: true } } }, orderBy: { createdAt: "desc" }, take: 500 }) }) }))
adminRouter.get("/quotes", asyncHandler(async (_req, res) => { res.json({ success: true, data: await prisma.quoteRequest.findMany({ orderBy: { createdAt: "desc" } }) }) }))
adminRouter.patch("/quotes/:id", asyncHandler(async (req, res) => {
  const data = z.object({ status: z.nativeEnum(QuoteStatus).optional(), adminNotes: z.string().optional() }).parse(req.body)
  const quote = await prisma.quoteRequest.update({ where: { id: req.params.id }, data })
  res.json({ success: true, data: quote })
}))
adminRouter.get("/bookings", asyncHandler(async (_req, res) => { res.json({ success: true, data: await prisma.booking.findMany({ include: { customer: { select: { name: true, email: true } }, vendor: { select: { businessName: true } } }, orderBy: { createdAt: "desc" } }) }) }))
adminRouter.patch("/bookings/:id", asyncHandler(async (req, res) => { const { status } = z.object({ status: z.nativeEnum(BookingStatus) }).parse(req.body); res.json({ success: true, data: await prisma.booking.update({ where: { id: req.params.id }, data: { status } }) }) }))
