import { Router } from "express"
import { OrderStatus, ProductStatus, Role } from "@prisma/client"
import { z } from "zod"
import { prisma } from "../lib/prisma.js"
import { authenticate, authorize } from "../middleware/auth.js"
import { asyncHandler } from "../middleware/async-handler.js"
import { AppError } from "../middleware/errors.js"

export const customerRouter = Router()
customerRouter.use(authenticate, authorize(Role.CUSTOMER))
customerRouter.patch("/profile", asyncHandler(async (req, res) => { const data = z.object({ name: z.string().min(2).optional(), phone: z.string().min(7).optional() }).parse(req.body); const user = await prisma.user.update({ where: { id: req.auth!.sub }, data, select: { id: true, name: true, email: true, phone: true, role: true } }); res.json({ success: true, data: user }) }))
customerRouter.get("/cart", asyncHandler(async (req, res) => { const carts = await prisma.cart.findMany({ where: { customerId: req.auth!.sub }, include: { vendor: { select: { id: true, businessName: true } }, items: { include: { product: true } } } }); res.json({ success: true, data: carts }) }))
customerRouter.post("/cart/items", asyncHandler(async (req, res) => { const input = z.object({ productId: z.string(), quantity: z.number().int().min(1).max(100) }).parse(req.body); const product = await prisma.product.findFirst({ where: { id: input.productId, status: ProductStatus.ACTIVE, vendor: { status: "APPROVED" } } }); if (!product) throw new AppError(404, "PRODUCT_NOT_FOUND", "Product is unavailable."); const cart = await prisma.cart.upsert({ where: { customerId_vendorId: { customerId: req.auth!.sub, vendorId: product.vendorId } }, update: {}, create: { customerId: req.auth!.sub, vendorId: product.vendorId } }); const item = await prisma.cartItem.upsert({ where: { cartId_productId: { cartId: cart.id, productId: product.id } }, update: { quantity: input.quantity, price: product.price }, create: { cartId: cart.id, productId: product.id, quantity: input.quantity, price: product.price } }); res.status(201).json({ success: true, data: item }) }))
customerRouter.delete("/cart/items/:id", asyncHandler(async (req, res) => { const item = await prisma.cartItem.findFirst({ where: { id: req.params.id, cart: { customerId: req.auth!.sub } } }); if (!item) throw new AppError(404, "CART_ITEM_NOT_FOUND", "Cart item not found."); await prisma.cartItem.delete({ where: { id: item.id } }); res.status(204).send() }))
customerRouter.post("/checkout", asyncHandler(async (req, res) => { const { cartId } = z.object({ cartId: z.string() }).parse(req.body); const cart = await prisma.cart.findFirst({ where: { id: cartId, customerId: req.auth!.sub }, include: { items: { include: { product: true } } } }); if (!cart || !cart.items.length) throw new AppError(400, "EMPTY_CART", "The selected cart is empty."); const commission = await prisma.commissionSetting.findUnique({ where: { id: "default" } }); const subtotal = cart.items.reduce((sum, item) => sum + Number(item.price) * item.quantity, 0); const platformFee = subtotal * Number(commission?.rate ?? 15) / 100; const order = await prisma.$transaction(async (tx) => { const created = await tx.order.create({ data: { customerId: req.auth!.sub, vendorId: cart.vendorId, orderNumber: `GE-${Date.now()}-${Math.floor(Math.random()*1000)}`, subtotal, platformFee, total: subtotal, items: { create: cart.items.map(item => ({ productId: item.productId, name: item.product.name, quantity: item.quantity, price: item.price })) } }, include: { items: true } }); await tx.cart.delete({ where: { id: cart.id } }); return created }); res.status(201).json({ success: true, data: order }) }))
customerRouter.get("/orders", asyncHandler(async (req, res) => { const orders = await prisma.order.findMany({ where: { customerId: req.auth!.sub }, orderBy: { createdAt: "desc" }, include: { items: true, vendor: { select: { businessName: true } } } }); res.json({ success: true, data: orders }) }))
customerRouter.get("/orders/:id", asyncHandler(async (req, res) => { const order = await prisma.order.findFirst({ where: { id: req.params.id, customerId: req.auth!.sub }, include: { items: true, vendor: true } }); if (!order) throw new AppError(404, "ORDER_NOT_FOUND", "Order not found."); res.json({ success: true, data: order }) }))
customerRouter.post("/bookings", asyncHandler(async (req, res) => { const data = z.object({ vendorId: z.string().optional(), eventType: z.string().min(2), eventDate: z.coerce.date(), guestCount: z.number().int().positive(), location: z.string().optional(), budget: z.number().positive().optional(), details: z.string().optional() }).parse(req.body); const booking = await prisma.booking.create({ data: { ...data, customerId: req.auth!.sub } }); res.status(201).json({ success: true, data: booking }) }))
customerRouter.get("/bookings", asyncHandler(async (req, res) => { const rows = await prisma.booking.findMany({ where: { customerId: req.auth!.sub }, orderBy: { createdAt: "desc" }, include: { vendor: { select: { businessName: true } } } }); res.json({ success: true, data: rows }) }))
customerRouter.patch("/orders/:id/cancel", asyncHandler(async (req, res) => { const order = await prisma.order.findFirst({ where: { id: req.params.id, customerId: req.auth!.sub } }); if (!order) throw new AppError(404, "ORDER_NOT_FOUND", "Order not found."); if (order.orderStatus !== OrderStatus.PENDING) throw new AppError(409, "ORDER_NOT_CANCELLABLE", "Only pending orders can be cancelled."); const updated = await prisma.order.update({ where: { id: order.id }, data: { orderStatus: OrderStatus.CANCELLED } }); res.json({ success: true, data: updated }) }))
